# Generated by Django 5.2.7 on 2025-11-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('admin', 'Administrator'), ('nurse', 'Nurse')], default='doctor', max_length=20),
        ),
    ]
